#!/bin/bash

# Build binary with sanitizer
# All smoke tests will run through sanitized binaries.

export ASAN_OPTIONS=symbolize=1
export ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer

# Chroot dir
ORIGIN_DIR=$PWD/../..
cd $ORIGIN_DIR
make sanitize

# Prepare
TMPDIR=$(mktemp -d /tmp/precizer.XXXXXXXXXXXXXXXXXX)
TESTDIRS="$TMPDIR/tests/examples/diffs/"
mkdir -p ${TESTDIRS}
cd ${TMPDIR}
cp -r $ORIGIN_DIR/tests/examples/diffs/diff* ${TESTDIRS}
cp -r $ORIGIN_DIR/libs/*/debug/*.so* ./
cp $ORIGIN_DIR/src/sanitize/precizer ./
#ls -laR

# Relative paths

precizer --progress tests/examples/diffs/diff1
#precizer --verbose --progress tests/examples/diffs/diff1
# Default database name
precizer --progress --database=database2.db tests/examples/diffs/diff2
HOSTNAME=$(hostname)
precizer --compare "${HOSTNAME}.db" database2.db


rm -rf ${TMPDIR}
